spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME} # environment variable
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none
ai:
  gemini:
    endpoint: ${AI_GENINI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/openai/chat/completions} # environment variable with a default value
    api-key: ${ai-gemini-api-key:your-genimi-api-key} # secret from Cloud Key Vault