spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
  jpa:
    show-sql: true
  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME:YOUR_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY:YOUR_ACCOUNT_KEY}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  data:
    redis:
      host: localhost
      port: 6379
ai:
  gemini:
    endpoint: ${AI_GENINI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/openai/chat/completions} # environment variable with a default value.
    api-key: ${AI_GENINI_API_KEY:YOUR_API_KEY} # environment variable with a default value
