spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
  jpa:
    show-sql: true
ai:
  gemini:
    endpoint: ${AI_GENINI_ENDPOINT:https://generativelanguage.googleapis.com/v1beta/openai/chat/completions} # environment variable with a default value.
    api-key: ${AI_GENINI_API_KEY:YOUR_API_KEY} # environment variable with a default value
